'use client';
import {useEffect,useRef,useState} from 'react';
import {Entry} from '../components/game/Entry';
import {RoleCard} from '../components/game/RoleCard';
import {Village} from '../components/game/Village';
import {Actions} from '../components/game/Actions';
import {Journal} from '../components/game/Journal';
import {Rules} from '../components/game/Rules';
import {PHASE_NAMES,ROLES,type GameView} from '../lib/game/model';
import {requestGame,type Session} from '../lib/game/client';
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[room,setRoom]=useState<GameView|null>(null),[joinCode,setJoinCode]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[hidden,setHidden]=useState(true),[copied,setCopied]=useState(false);
 const offset=useRef(0),version=useRef(0),latest=useRef<GameView|null>(null);
 function accept(r:GameView){offset.current=r.serverNow-Date.now();latest.current=r;setRoom(r);}
 useEffect(()=>{try{const raw=sessionStorage.getItem('yemu-seat');if(raw)setSession(JSON.parse(raw));}catch{}setJoinCode(new URLSearchParams(location.search).get('room')??'');setLoaded(true);const timer=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!session)return;let live=true;let timer:ReturnType<typeof setTimeout>;async function poll(){const n=version.current;try{const d=await requestGame('poll',session);if(live&&n===version.current)accept(d.room);}catch(e){if(live)setError(e instanceof Error?e.message:'正在重新连接…');}finally{if(live)timer=setTimeout(poll,1000);}}void poll();return()=>{live=false;clearTimeout(timer);};},[session]);
 useEffect(()=>{(window as unknown as {render_game_to_text:()=>string}).render_game_to_text=()=>JSON.stringify(latest.current??{phase:'entry'});const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'read_werewolf_view',description:'Read the same room information visible to this player, including their own private identity and checks. Never returns other players’ secret roles.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>latest.current??{phase:'entry'}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 async function action(action:string,data:Record<string,unknown>={}){setBusy(true);setError('');version.current++;try{const result=await requestGame(action,session,data);if(result.token){const next={code:result.room.code,token:result.token};sessionStorage.setItem('yemu-seat',JSON.stringify(next));setSession(next);history.replaceState(null,'',`?room=${next.code}`);setHidden(true);}if(action==='leave'){sessionStorage.removeItem('yemu-seat');setSession(null);setRoom(null);latest.current=null;history.replaceState(null,'',location.pathname);}else{if(action==='rematch')setHidden(true);accept(result.room);}return true;}catch(e){setError(e instanceof Error?e.message:'操作失败。');return false;}finally{setBusy(false);version.current++;}}
 const seconds=room?Math.max(0,Math.ceil((room.deadline-now-offset.current)/1000)):0;
 return <main className="shell"><header><a className="brand" href="/" onClick={e=>{if(room)e.preventDefault();}}>☾ <span>夜幕<small>狼人杀</small></span></a>{room?<div className="room-tools"><button className="code-button" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError(`请分享房间号：${room.code}`);}}}>{copied?'已复制邀请链接':`房间 ${room.code} ↗`}</button>{(room.phase==='lobby'||room.phase==='finished'||room.isSpectator)&&<button className="text-button" disabled={busy} onClick={()=>action('leave')}>离开</button>}</div>:<span className="header-note">秘密身份 · 在线同局</span>}</header>{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="关闭提示">×</button></div>}{!room?<>{loaded&&<Entry key={joinCode} joinCode={joinCode} busy={busy} act={action}/>}{session&&<button className="text-button" onClick={()=>{sessionStorage.removeItem('yemu-seat');setSession(null);setError('');}}>重新选择房间</button>}<Rules/></>:<><div className="phase-bar"><div><span className="kicker">{room.phase==='lobby'?'等待室':room.phase==='finished'?'终局':`第 ${room.day} ${room.phase.startsWith('night')?'夜':'天'}`}</span><h1>{PHASE_NAMES[room.phase]}</h1></div><div className="phase-steps"><span className={room.phase.startsWith('night')?'current':''}>01 夜间</span><span className={room.phase==='speech'?'current':''}>02 发言</span><span className={room.phase==='vote'?'current':''}>03 投票</span></div>{room.deadline>0&&<div className="clock" aria-label="剩余时间">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</div>}</div><div className="game-layout"><aside className="identity-panel"><div className="section-heading"><h2>{room.isSpectator?'观战席':'我的身份'}</h2><span>仅自己可见</span></div><RoleCard role={room.myRole} hidden={hidden&&room.phase!=='finished'}/>{room.myRole&&<button className="secondary reveal-role" onClick={()=>setHidden(!hidden)}>{hidden?'翻开身份':'收起身份'}</button>}<p className="role-tip">{room.isSpectator?'本局只观看，下局可以入座。':room.phase==='lobby'?'开局后随机发牌。先邀请朋友，或添加 AI 玩家。':hidden?'请确认周围没有其他玩家再翻牌。':room.myRole?ROLES[room.myRole].tip:''}</p>{room.checks.length>0&&<section className="private-notes"><h3>我的查验</h3>{room.checks.map(c=><p key={`${c.day}-${c.target}`}>第 {c.day} 夜 · {room.players.find(p=>p.id===c.target)?.seat} 号 <strong className={c.wolf?'red':''}>{c.wolf?'狼人':'好人'}</strong></p>)}</section>}</aside><div className="game-center"><Village room={room} busy={busy} act={action}/><Actions key={`${room.phase}-${room.day}-${room.speaker??''}-${room.pk}`} room={room} busy={busy} act={action}/><Rules preset={room.preset}/></div><Journal room={room} busy={busy} act={action}/></div></>}</main>;
}
