import {systemText} from '../../lib/i18n/translate';
import {useLanguage} from '../../lib/i18n/context';
import {useState} from 'react';
import {PRESETS,PHASE_NAMES,type GameView} from '../../lib/game/model';
export function Actions({room,busy,act}:{room:GameView;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<boolean>}){
 const {t,lang}=useLanguage();
 const [selected,setSelected]=useState('');const host=room.host===room.you,me=room.players.find(p=>p.id===room.you);
 if(room.phase==='lobby')return <section className="action-panel"><div className="section-heading"><h2>{t("房间配置")}</h2><span>{t("房主设置")}</span></div><div className="preset-options">{Object.entries(PRESETS).map(([key,p])=><button key={key} className={room.preset===key?'selected':''} aria-pressed={room.preset===key} disabled={!host||busy} onClick={()=>act('preset',{preset:key})}><strong>{t(p.name)}</strong><small>{t(p.description)}</small></button>)}</div><p className="preset-rule">{t(PRESETS[room.preset].rule)}</p><label className="setting-row">{t("每人发言时间")}<select aria-label={t("发言时间")} value={room.speechSeconds} disabled={!host||busy} onChange={e=>act('settings',{seconds:Number(e.target.value)})}>{[20,30,45,60].map(n=><option key={n} value={n}>{n} {t("秒")}</option>)}</select></label><div className="lobby-buttons">{host&&<button className="secondary" disabled={busy||room.players.length>=PRESETS[room.preset].size} onClick={()=>act('fill')}>{t("补齐 AI 玩家")}</button>}{me&&<button className="secondary" disabled={busy} onClick={()=>act('ready')}>{me.ready?t("取消准备"):t("我准备好了")}</button>}{host&&<button className="primary" disabled={busy||room.players.length!==PRESETS[room.preset].size||!room.players.every(p=>p.ready)} onClick={()=>act('start')}>{t("开始游戏")}</button>}</div><p className="small-note">{t("所有真人准备后开局。可以一人练习，也可以多设备同局。")}</p></section>;
 if(room.phase==='finished')return <section className={`action-panel final-result ${room.winner==='wolves'?'wolf-result':''}`}><p className="kicker">{t("最终结果")}</p><h2>{room.winner==='good'?t("好人阵营获胜"):room.winner==='wolves'?t("狼人阵营获胜"):t("本局平局")}</h2><p>{systemText(room.winReason??'',lang)}</p><p className="muted">{t("所有身份已公开。可以回看发言与票型，比较谁说了真话。")}</p>{host?<button className="primary" disabled={busy} onClick={()=>act('rematch')}>{t("再开一局")}</button>:<p>{t("等待房主开始下一局")}</p>}</section>;
 const speaker=room.players.find(p=>p.id===room.speaker);
 return <section className="action-panel"><p className="kicker">{room.phase.startsWith('night')?t("夜间行动 · 私密"):t("当前行动")}</p><h2>{room.isSpectator?t("你正在观战"):room.phase==='speech'||room.phase==='lastWords'?lang==='en'?`Seat ${speaker?.seat??''} · ${room.phase==='lastWords'?'Last words':'Speaking'}`:`${speaker?.seat??''} 号${room.phase==='lastWords'?'遗言':'发言'}`:t(PHASE_NAMES[room.phase])}</h2>{room.phase==='nightWolf'&&room.myRole==='wolf'&&room.myAlive&&<p className="action-hint">{t("在狼队私聊中统一目标。")}{room.wolfVotes?.map(v=>`${v.name}：${v.target?(v.target==='none'?t("空刀"):`${lang==='en'?'Seat ':''}${room.players.find(p=>p.id===v.target)?.seat}${lang==='en'?'':'号'}`):t("未选")}`).join(' / ')}</p>}{room.phase==='nightWitch'&&room.myRole==='witch'&&<p className="action-hint">{room.potions?.save?(room.wolfTarget?lang==='en'?`Tonight’s target: Seat ${room.players.find(p=>p.id===room.wolfTarget)?.seat} ${room.wolfTarget===room.you?'(cannot save yourself)':''}. `:`今晚受袭的是 ${room.players.find(p=>p.id===room.wolfTarget)?.seat} 号${room.wolfTarget===room.you?t("（不能自救）"):''}。`:t("今晚没有狼刀目标。")):t("解药已用完，不再显示狼刀目标。")}{t("解药：")}{room.potions?.save?'1':'0'}{t("· 毒药：")}{room.potions?.poison?'1':'0'}</p>}{room.pk&&<p className="action-hint">PK：{room.tied.map(id=>room.players.find(p=>p.id===id)?.seat).join('、')}{t("号。平票者不能参与复投。")}</p>}{room.options.length>0?<><div className="action-options">{room.options.map(o=><button key={o.value} className={(room.myChoice??selected)===o.value?'selected':''} aria-pressed={(room.myChoice??selected)===o.value} disabled={busy||!room.canAct} onClick={()=>setSelected(o.value)}>{systemText(o.label,lang)}</button>)}</div><button className="primary" disabled={busy||!room.canAct||!selected} onClick={()=>act('choice',{value:selected})}>{room.myChoice?t("已确认 · 等待阶段结束"):t("确认选择")}</button><p className="small-note">{t("确认后无法修改。超时未选择视为跳过。")}</p></>:<p className="action-hint">{room.isSpectator?t("观战不会显示其他人的秘密身份。下一局有空位时自动入座。"):!room.myAlive&&room.speaker!==room.you?t("你已出局，可以继续观看。"):room.speaker===room.you?t("请在发言区输入你的分析，完成后结束发言。"):room.phase==='dawn'?t("请查看右侧记录中的出局名单。"):room.phase.startsWith('night')?t("请等待其他角色行动。每个夜间阶段固定 15 秒。"):t("请听取当前玩家的发言。")}</p>}{room.speaker===room.you&&<button className="primary" disabled={busy} onClick={()=>act('endSpeech')}>{t("发言结束")}</button>}</section>;
}
