import {useState} from 'react';
import {PRESETS,PHASE_NAMES,type GameView} from '../../lib/game/model';
export function Actions({room,busy,act}:{room:GameView;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<boolean>}){
 const [selected,setSelected]=useState('');const host=room.host===room.you,me=room.players.find(p=>p.id===room.you);
 if(room.phase==='lobby')return <section className="action-panel"><div className="section-heading"><h2>房间配置</h2><span>房主设置</span></div><div className="preset-options">{Object.entries(PRESETS).map(([key,p])=><button key={key} className={room.preset===key?'selected':''} aria-pressed={room.preset===key} disabled={!host||busy} onClick={()=>act('preset',{preset:key})}><strong>{p.name}</strong><small>{p.description}</small></button>)}</div><p className="preset-rule">{PRESETS[room.preset].rule}</p><label className="setting-row">每人发言时间<select aria-label="发言时间" value={room.speechSeconds} disabled={!host||busy} onChange={e=>act('settings',{seconds:Number(e.target.value)})}>{[20,30,45,60].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label><div className="lobby-buttons">{host&&<button className="secondary" disabled={busy||room.players.length>=PRESETS[room.preset].size} onClick={()=>act('fill')}>补齐 AI 玩家</button>}{me&&<button className="secondary" disabled={busy} onClick={()=>act('ready')}>{me.ready?'取消准备':'我准备好了'}</button>}{host&&<button className="primary" disabled={busy||room.players.length!==PRESETS[room.preset].size||!room.players.every(p=>p.ready)} onClick={()=>act('start')}>开始游戏</button>}</div><p className="small-note">所有真人准备后开局。可以一人练习，也可以多设备同局。</p></section>;
 if(room.phase==='finished')return <section className={`action-panel final-result ${room.winner==='wolves'?'wolf-result':''}`}><p className="kicker">最终结果</p><h2>{room.winner==='good'?'好人阵营获胜':room.winner==='wolves'?'狼人阵营获胜':'本局平局'}</h2><p>{room.winReason}</p><p className="muted">所有身份已公开。可以回看发言与票型，比较谁说了真话。</p>{host?<button className="primary" disabled={busy} onClick={()=>act('rematch')}>再开一局</button>:<p>等待房主开始下一局</p>}</section>;
 const speaker=room.players.find(p=>p.id===room.speaker);
 return <section className="action-panel"><p className="kicker">{room.phase.startsWith('night')?'夜间行动 · 私密':'当前行动'}</p><h2>{room.isSpectator?'你正在观战':room.phase==='speech'||room.phase==='lastWords'?`${speaker?.seat??''} 号${room.phase==='lastWords'?'遗言':'发言'}`:PHASE_NAMES[room.phase]}</h2>{room.phase==='nightWolf'&&room.myRole==='wolf'&&room.myAlive&&<p className="action-hint">在狼队私聊中统一目标。{room.wolfVotes?.map(v=>`${v.name}：${v.target?(v.target==='none'?'空刀':`${room.players.find(p=>p.id===v.target)?.seat}号`):'未选'}`).join(' / ')}</p>}{room.phase==='nightWitch'&&room.myRole==='witch'&&<p className="action-hint">{room.potions?.save?(room.wolfTarget?`今晚受袭的是 ${room.players.find(p=>p.id===room.wolfTarget)?.seat} 号${room.wolfTarget===room.you?'（不能自救）':''}。`:'今晚没有狼刀目标。'):'解药已用完，不再显示狼刀目标。'} 解药：{room.potions?.save?'1':'0'} · 毒药：{room.potions?.poison?'1':'0'}</p>}{room.pk&&<p className="action-hint">PK：{room.tied.map(id=>room.players.find(p=>p.id===id)?.seat).join('、')} 号。平票者不能参与复投。</p>}{room.options.length>0?<><div className="action-options">{room.options.map(o=><button key={o.value} className={(room.myChoice??selected)===o.value?'selected':''} aria-pressed={(room.myChoice??selected)===o.value} disabled={busy||!room.canAct} onClick={()=>setSelected(o.value)}>{o.label}</button>)}</div><button className="primary" disabled={busy||!room.canAct||!selected} onClick={()=>act('choice',{value:selected})}>{room.myChoice?'已确认 · 等待阶段结束':'确认选择'}</button><p className="small-note">确认后无法修改。超时未选择视为跳过。</p></>:<p className="action-hint">{room.isSpectator?'观战不会显示其他人的秘密身份。下一局有空位时自动入座。':!room.myAlive&&room.speaker!==room.you?'你已出局，可以继续观看。':room.speaker===room.you?'请在发言区输入你的分析，完成后结束发言。':room.phase==='dawn'?'请查看右侧记录中的出局名单。':room.phase.startsWith('night')?'请等待其他角色行动。每个夜间阶段固定 15 秒。':'请听取当前玩家的发言。'}</p>}{room.speaker===room.you&&<button className="primary" disabled={busy} onClick={()=>act('endSpeech')}>发言结束</button>}</section>;
}
