import {useLanguage} from '../../lib/i18n/context';
import {useState} from 'react';
import {RoleArt} from './RoleCard';
import {ROLES,type Role} from '../../lib/game/model';
export function Entry({joinCode,busy,act}:{joinCode:string;busy:boolean;act:(action:string,data:Record<string,unknown>)=>Promise<boolean>}){
 const {t,lang}=useLanguage();
 const [name,setName]=useState(''),[code,setCode]=useState(joinCode),[role,setRole]=useState<Role>('seer');
 const info=ROLES[role];
 return <section className="entry"><div className="role-showcase"><div className="showcase-art" key={role}><RoleArt role={role}/><div className="showcase-shade"/><div className="showcase-title"><span className="role-team">{t(info.team)}</span><h1>{t(info.name)}</h1></div></div><div className="role-tabs" aria-label={t("了解角色")}>{Object.entries(ROLES).map(([key,r])=><button key={key} aria-pressed={role===key} onClick={()=>setRole(key as Role)}>{t(r.name)}</button>)}</div><p className="role-description">{t(info.ability)}</p><small className="muted">{t("这里仅介绍角色。开局后随机分配秘密身份。")}</small></div><div className="entry-panel"><p className="kicker">{t("夜幕 / 狼人杀")}</p><h2>{t("进入今晚的村庄")}</h2><form onSubmit={e=>{e.preventDefault();void act('create',{name});}}><label htmlFor="name">{t("你的名字")}</label><input id="name" value={name} onChange={e=>setName(e.target.value)} placeholder={t("输入昵称")} maxLength={16} required/><button className="primary" disabled={busy||!name.trim()}>{busy?t("连接中…"):t("创建房间")}</button></form><div className="divider">{t("或加入朋友")}</div><form onSubmit={e=>{e.preventDefault();void act('join',{name,code});}}><label className="sr-only" htmlFor="join-code">{t("房间号")}</label><input id="join-code" placeholder={t("五位房间号")} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={5} required/><button className="secondary" disabled={busy||!name.trim()||code.length!==5}>{t("加入房间")}</button></form><small>{t("6 / 9 / 12 人配置 · 可用 AI 补齐人数")}<br/>{t("与朋友从各自设备加入同一房间")}</small></div></section>;
}
