import {systemText} from '../../lib/i18n/translate';
import {useLanguage} from '../../lib/i18n/context';
import {useState,useEffect,useRef} from 'react';
import type {GameView} from '../../lib/game/model';
export function Journal({room,busy,act}:{room:GameView;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<boolean>}){
 const {t,lang}=useLanguage();
 const [text,setText]=useState(''),end=useRef<HTMLDivElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[room.messages.length]);
 const name=(id:string|null)=>room.players.find(p=>p.id===id)?.seat??t("弃票");
 return <aside className="journal"><section className="events"><h2>{t("村庄记录")}</h2><div>{room.logs.length?room.logs.slice(-8).map(e=><p key={e.id}><small>{lang==='en'?`Day ${e.day}`:`第 ${e.day} 天`}</small>{systemText(e.text,lang)}</p>):<p className="muted">{t("开局后的公开事件会记录在这里。")}</p>}</div></section><section className={`discussion ${room.chatChannel==='wolves'?'wolf-chat':''}`}><div className="section-heading"><h2>{room.chatChannel==='wolves'?t("狼队私聊"):t("发言记录")}</h2><span>{room.canChat?t("可以发言"):t("聆听中")}</span></div><div className="messages" aria-live="polite">{!room.messages.length&&<p className="empty-copy">{t("发言、查验声明与质疑会保留在这里。玩家可能说谎。")}</p>}{room.messages.map(m=><article key={m.id} className={m.channel==='wolves'?'private-message':''}><div><strong>{lang==='en'?`Seat ${name(m.author)} · `:`${name(m.author)} 号 · `}{m.name}</strong><small>{m.channel==='wolves'?t("仅狼队可见"):lang==='en'?`Day ${m.day}`:`第 ${m.day} 天`}</small></div><p>{room.players.find(p=>p.id===m.author)?.bot?systemText(m.text,lang):m.text}</p></article>)}<div ref={end}/></div><form onSubmit={async e=>{e.preventDefault();if(await act('chat',{text}))setText('');}}><label className="sr-only" htmlFor="message">{t("发言内容")}</label><textarea id="message" value={text} onChange={e=>setText(e.target.value)} maxLength={400} disabled={!room.canChat} placeholder={room.canChat?(room.chatChannel==='wolves'?t("仅存活狼队可以在此讨论…"):t("输入你的分析…")):t("等待你的发言轮次…")} rows={3}/><button className="secondary" disabled={busy||!room.canChat||!text.trim()}>{t("发送发言")}</button></form></section><details className="ballots"><summary>{lang==='en'?`Public votes · ${room.ballots.length} rounds`:`公开票型 · ${room.ballots.length} 轮`}</summary>{room.ballots.map((b,i)=><div key={i}><h3>{lang==='en'?`Day ${b.day}`:`第 ${b.day} 天`}{b.pk?t(" · PK 复投"):''}</h3>{b.votes.map(v=><p key={v.voter}>{lang==='en'?`Seat ${name(v.voter)} → `:`${name(v.voter)} 号 → `}{v.target?lang==='en'?`Seat ${name(v.target)}`:`${name(v.target)} 号`:t("弃票")}</p>)}<strong>{b.eliminated?lang==='en'?`Seat ${name(b.eliminated)} eliminated`:`${name(b.eliminated)} 号出局`:t("无人出局 / 进入 PK")}</strong></div>)}</details></aside>;
}
